#[cfg(test)]
use battlesnake_game_of_chicken_lib::{OriginalDirection, get_move_from_json_file};
#[macro_use]
mod common;

situation_test!(failure_01, Down, Left, Right);
situation_test!(failure_02, Up, Down, Left);
situation_test!(failure_03, Down);
situation_test!(failure_04, Up, Left);
situation_test!(failure_05, Up);
situation_test!(failure_06, Left, Right);
situation_test!(failure_07, Left, Right);
situation_test!(failure_08, Down);
situation_test!(failure_09, Up, Down, Right => "All other situations are barely survivable by using all available space");
situation_test!(failure_10, Left);
situation_test!(failure_11, Left);
situation_test!(failure_12, Left);
situation_test!(failure_13, Left, Right);
situation_test!(failure_14, Up, Left, Right);
situation_test!(failure_15, Left, Right);
situation_test!(failure_16, Left, Right);
situation_test!(failure_17, Down);
situation_test!(failure_18, Down, Left);
situation_test!(failure_19, Up, Down);
situation_test!(failure_20, Down => "Going left leads to death when B goes up and then right, as there is not enough space");
situation_test!(failure_21, Right => "bait into trap with top wall");
situation_test!(failure_22, Right => "bait into trap with top wall modified");
situation_test!(failure_23, Down, Right => "Down leads to guaranteed kill in 2, right leads to guaranteed kill in 4");
situation_test!(failure_24, Down, Left, Right => "debug space");
situation_test!(failure_25, Down => "continue down for kill");
situation_test!(failure_26, Down => "continue down for kill");
situation_test!(failure_27, Left => "grab food");
situation_test!(failure_28, Down => "grab food");
situation_test!(failure_29, Down => "move down towards food");
situation_test!(failure_30, Down, Right => "grab food leads to death");
situation_test!(failure_31, Down, Left => "going right leads to death");
situation_test!(failure_32, Down, Right => "Assuming perfect opponent play, right is best (certain death in 3 turns); down better if opponents play imperfectly");
situation_test!(failure_33, Up, Right => "do not move left as you can get killed");
situation_test!(failure_34, Left, Right => "Too long to really evaluate with current visualisation tools, therefore left and right accepted");
situation_test!(failure_35, Up, Down => "Up is dead in 3, down is dead in 8");
situation_test!(failure_36, Right => "tail 2 food 4");
situation_test!(failure_37, Down, Left, Right => "unclear best move");
situation_test!(failure_38, Left, Right => "Moving right would equally allow for squeeze");
situation_test!(failure_39, Left => "This might be fixed with chicken logic or adding length to simulate timed evaluation");
situation_test!(failure_40, Up, Right => "should go up to food");
situation_test!(failure_41, Left => "area suggests right but left might be better");
situation_test!(failure_42, Down, Right => "going right enables getting killed");
situation_test!(failure_43, Up => "going down guarantees getting killed");
situation_test!(failure_44, Up, Left, Right => "panic");
situation_test!(failure_45, Right => "panic again");
situation_test!(failure_46, Right => "go for kill");
situation_test!(failure_47, Down => "grab food");
situation_test!(failure_48, Left => "Depending on what B does next it is always possible to escape; move choice must depend on B's response");
situation_test!(failure_49, Down => "Failed when L,D,R reached depth 10 by only selecting L as viable from simulation");
situation_test!(failure_50, Left => "Failed when L,D,R reached depth 10 by only selecting L as viable from simulation");
situation_test!(failure_51, Up, Down => "grab food after other moved down in 48");
situation_test!(failure_52, Up, Down => "grab food after other moved up in 48");
situation_test!(failure_53, Left => "go for kill");
situation_test!(failure_54, Right => "grab food");
situation_test!(failure_55, Up, Down, Left);
situation_test!(failure_56, Down, Right);
situation_test!(failure_57, Up);
situation_test!(failure_58, Down, Left, Right);
situation_test!(failure_59, Up => "Going up should be possible but is being excluded by capture logic");
situation_test!(failure_60, Up => "Going up is preferrable here to fight for the food");
situation_test!(failure_61, Up => "Squeezing logic from flood prefers down but there is too much going on");
situation_test!(failure_62, Left => "Moved to wall because of food, but should move away again now");
situation_test!(failure_63, Up => "Is grabbing food preferred here?");
situation_test!(failure_64, Left => "Left is preferable to right as death relies on opponent move, whereas right is inevitable death");
situation_test!(failure_65, Right => "Right is preferable to left as death relies on opponent move, whereas left is inevitable death");
situation_test!(failure_66, Left => "Going Left should be possible here");
situation_test!(failure_67, Right => "Right is preferable to left as death relies on opponent move, whereas left is inevitable death");
situation_test!(failure_68, Right => "Right is preferable to left as death relies on opponent move, whereas left is inevitable death");
situation_test!(failure_69, Right => "Right is preferable to left as death relies on opponent move, whereas left is inevitable death");
situation_test!(failure_70, Right => "Hash pruning problem case falsely identifies WinnerIn, also we will be shorter if going left probably");
situation_test!(failure_71, Down => "Going down allows for chasing tails");
situation_test!(failure_72, Up => "Going up allows for chasing tails, going down not because of B");
situation_test!(failure_73, Up => "Bad situation overall, but up allows for risky plays whereas right is almost certain death against capable opponent");
situation_test!(failure_74, Up, Down => "Pruning problem, false winner in simulation suggests right");
situation_test!(failure_75, Up => "Pruning problem, left is seen as alive although it is not if B eats food");
situation_test!(failure_76, Left => "Left is fastest way to win");
situation_test!(failure_77, Down => "Right leads to probably dead, but massive tree growth, probably requires pruning");
situation_test!(failure_78, Right => "Grabbing the food equalises length which would help massively");
situation_test!(failure_79, Right, Up => "Going left (and then down) leads to death by D");
situation_test!(failure_80, Left => "Get out of the triangle formed by the other snake heads");
situation_test!(failure_81, Up, Right => "Going down leads to beeing trapped");
situation_test!(failure_82, Left, Right => "Both directions lead to death, not sure which is better");
situation_test!(failure_83, Left, Right => "Down leads to death, right not sure about it");
